### ISSUE TITLE
[Feature] Pull to refresh

### ISSUE THREAD

**Issue by dbof10** [NikolayNIK/material_table_view#12]
Is the feature available in the lib already or can you suggest how to do that?

**Comment by NikolayNIK** [comment]
Just out of curiosity, did you find a solution? I haven't thought about that feature at all

**Comment by NikolayNIK** [comment]
For anyone that might stumble across this issue: I've fixed the `TableView` to work with `RefreshIndicator`  from Flutters material library. `SliverTableView` worked from the start. The fix is available in version `4.0.2`.

Also I've updated demo to include progress indicators. Thank you @dbof10 for bringing this issue to my attention.

**Comment by abdullahhamdan-gh** [comment]
Hi @dbof10 @NikolayNIK 
Did you find any solution for making load more functionality (from `pull_to_refresh`) work with `TableView.builder`?

**Comment by NikolayNIK** [comment]
> Hi [@dbof10](https://github.com/dbof10) [@NikolayNIK](https://github.com/NikolayNIK) Did you find any solution for making load more functionality (from `pull_to_refresh`) work with `TableView.builder`?

Hi. Personally, I haven't tested `pull_to_refresh` or any other third party libraries for that matter. Given that this project uses built-in Flutter scrolling mechanisms, I suspect it should work right out of the gate or at least it should be possible to make it so.
