### ISSUE TITLE
How to pin the header of table when scrolling up

### ISSUE THREAD

**Issue by khangpt** [NikolayNIK/material_table_view#16]
As mentioned on title of this thread. Can you guide me the tip for this

Thanks

**Comment by NikolayNIK** [comment]
The `headerBuilder` argument is used to create a static row at the top of the table which does not get scrolled vertically. [Here](https://github.com/NikolayNIK/material_table_view_demo/blob/bc3cc6cf51cad7cb82c18a35fad96a9d8e37d5b6/lib/main.dart#L338) is an example of such a function in the demo.

Let me know if this is not what you meant.

**Comment by khangpt** [comment]
@NikolayNIK I found it. In CustomScrollView, if I push any SliverPersistentHeader above SliverTableView, it seem not pin the header of Table on top anymore, when I remove the persistent header right away, it return to work perfectly.

Can you investigate this issue?

**Comment by NikolayNIK** [comment]
> @NikolayNIK I found it. In CustomScrollView, if I push any SliverPersistentHeader above SliverTableView, it seem not pin the header of Table on top anymore, when I remove the persistent header right away, it return to work perfectly.
> 
> Can you investigate this issue?

@khangpt, oh yeah, now I see. The `SliverPersistentHeader` gets layed out on top of the header of a `SliverTableView` preventing it from being seen. It seems to me like it is expected behavior of the `SliverPersistentHeader` as it is assumed that no meaningful content would become invisible (like in the case of a list).

Wrapping `SliverPersistentHeader` in a `SliverOverlapAbsorber` with a dummy `handle` seems to resolve the issue by actually changing the layout of the slivers after the header. Alhough it makes the scrolling of table rows effectively double (actual scroll plus persistent header shifting the layout). Listening to the `handle` does not seem to provide a way of correcting this behavior and I can't think of anything else.

Although this does not seem like an issue of the `material_table_view`, the discussion here might be useful to anyone facing a similar problem.

**Comment by mai-dev-j** [comment]
@NikolayNIK 

I want to make the SliverTableView header works like the other pinned headers (list 1, list 2, table ) in SliverMainAxisGroup, but it always go behind the first PinnedHeaderSliver, could you help? thanks!

```dart
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("title"),
        centerTitle: true,
      ),
      body: CustomScrollView(
        controller: scrollController,
        slivers: [
          PinnedHeaderSliver(
            child: Container(
                height: 100,
                color: Colors.blueAccent,
                child: const Center(child: Text('Top Pinned Header'))),
          ),
          SliverMainAxisGroup(slivers: [
            PinnedHeaderSliver(
              child: Card(margin: EdgeInsets.zero, child: Text('list 1', style: TextStyle(fontSize: 30))),
            ),
            SliverList.builder(itemBuilder: (c, i) => Text("list item 1-${i}"), itemCount: 20,),
          ]),
          SliverMainAxisGroup(slivers: [
            PinnedHeaderSliver(
              child: Card(margin: EdgeInsets.zero, child: Text('list 2', style: TextStyle(fontSize: 30))),
            ),
            SliverList.builder(itemBuilder: (c, i) => Card(child: Text("list item 2-${i}")), itemCount: 20,),
          ]),
          PinnedHeaderSliver(
            child: Card(margin: EdgeInsets.zero, child: Text('table', style: TextStyle(fontSize: 30))),
          ),
          SliverTableView.builder(...),
        ],
      ),
    )
```


https://github.com/user-attachments/assets/c522cb7f-dcbd-4577-9552-86d9575afa83
